### PR TITLE
Improve the user experience of the ItemStatsEditor

### PR DESCRIPTION
**Pull request by ziio2110**

### CODE REVIEW

**Comment by spg-stany** [comment]
[ziio2110](https://github.com/ziio2110) good idea but there are a few things
rubbish in names to be cleaned
numbering stats looks redundant
I didn’t understand how filtering works, it seems that each field should have a filter and not a common one for all fields

image

**Comment by ziio2110** [comment]
Hi! [spg-stany](https://github.com/spg-stany)

> rubbish in names to be cleaned

- Right, but I think it's better than the original short stat title (which sometimes could not provide enough information). More efferts were needed to clean these rubbishes.

> numbering stats looks redundant

- I was making several small charms, each of which contains all the skills of a particular class. I need these numbers to make sure the amount of skills is correct.

> about filtering, it seems that each field should have a filter and filtering runtime by input

- The filter is used only when I want to ***add a new stat***. So currently there is only one filter. More specifically, I was making something like this: xx
- I understand why there could be one filter for each field. I tried another way to implement filter by using the `Select2` module that has been existed in current repository, which can provide each field a filter, but it seems to be difficult to update data correctly in `v-for` with `Select2` or `v-select`. So I turned to this more simpler way.

**Comment by spg-stany** [comment]
[ziio2110](https://github.com/ziio2110)
you can enable filter easy way that <select> .. v-select </select>
it is better way, but it should have a problem https://github.com/dschu012/d2s-editor/issues/80
i will fix it later

**Review by spg-stany — CHANGES_REQUESTED** [review]
review in conversation

**Pull request closed without merging**
