### PR TITLE
refactoring on vue for filtering in select

### PR DESCRIPTION
**Pull request by spg-stany**
#142 
#146
#80

### CODE REVIEW

**Comment by spg-stany** [comment]
hi @dschu012 
I did a lot of work so that there were filters in the select and the data was not multiplied, I came to the decision to create vue component wrapper for select2
now I need your help with deploying the project from the directory ./dist or any variant you choises

**Comment by dschu012** [comment]
Can you change the dir it builds to to `./doc`

**Comment by spg-stany** [comment]
> Can you change the dir it builds to to `./doc` (and also commit the built files). After that is the PR ready to merge and have this change?

@dschu012 done

**Comment by dschu012** [comment]
darnit it was supposed to be `./docs` actually. I just pushed that change to master.

**Comment by spg-stany** [comment]
> darnit it was supposed to be `./docs` actually. I just pushed that change to master. think everything is deployed alright?
> 
> image
> 
> I see the built js files.

success
ty

**Pull request merged**
